In [1]:
import numpy as np
y = np.random.random([2,2])
x = np.random.random([2,2])
y = y * 10
x = x * 10

In [2]:
y.shape

(2, 2)

In [3]:
#y.transpose()

In [4]:
x

array([[7.89660638, 8.35327693],
       [5.16670376, 8.58482779]])

In [5]:
y

array([[6.42639832, 1.44637749],
       [4.11476677, 0.0472408 ]])

In [6]:
x * y

array([[50.74673803, 12.08199174],
       [21.25978094,  0.40555414]])

In [7]:
np.matmul(x,y)

array([[85.11852436, 11.81608923],
       [68.52786053,  7.87855817]])

In [8]:
np.exp(x) #raises e to x

array([[2688.14430046, 4244.06548613],
       [ 175.3359347 , 5349.87135774]])

In [9]:
np.sin(x)

array([[ 0.9990917 ,  0.8779202 ],
       [-0.89856195,  0.74460986]])

In [10]:
hmm = np.array([4,2,9,-6,5,11,3])
np.max(hmm)

11

In [11]:
np.min(hmm)

-6

In [12]:
hmm.max()

11

In [13]:
np.random.random([2,1])

array([[0.96062832],
       [0.59256695]])

In [14]:
np.random.random()

0.43534823453624627

In [15]:
np.linalg.norm(hmm) #finds the norm

17.08800749063506

In [16]:
def scalar(x,y):
    return x + y

In [18]:
#Converts this to a vecotr function
def vector(x,y):
    return np.vectorize(scalar)(x,y)
vector(x,y)

array([[14.32300471,  9.79965442],
       [ 9.28147053,  8.6320686 ]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])