In [32]:
import numpy as np
y = np.random.random([2,2])
x = np.random.random([2,2])
y = y * 10
x = x * 10

In [33]:
y.shape

(2, 2)

In [34]:
#y.transpose()

In [38]:
x

array([[8.75800934, 8.94525353],
       [3.0039501 , 4.26361433]])

In [39]:
y

array([[8.84556627, 5.26482373],
       [3.00546307, 0.07495926]])

In [35]:
x * y

array([[77.46955201, 47.09518303],
       [ 9.02826112,  0.31959739]])

In [36]:
np.matmul(x,y)

array([[104.35418119,  46.77990498],
       [ 39.38577515,  16.13486517]])

In [37]:
np.exp(x) #raises e to x

array([[6361.43551739, 7671.39328488],
       [  20.1650338 ,   71.06637722]])

In [40]:
np.sin(x)

array([[ 0.61844992,  0.46135729],
       [ 0.13720834, -0.90097941]])

In [43]:
hmm = np.array([4,2,9,-6,5,11,3])
np.max(hmm)

11

In [44]:
np.min(hmm)

-6

In [45]:
hmm.max()

11

In [47]:
np.random.random([2,1])

array([[0.20955872],
       [0.43804623]])

In [48]:
np.random.random()

0.5670410983646885

In [49]:
np.linalg.norm(hmm) #finds the norm

17.08800749063506